Don't call `transform` if it isn't defined.
nemo/through2-batch pull request #2
Opened 2018-04-06 02:47 UTC by wtgtybhertgeghgtwtg

`transform` is called in `_flush`, even if the user didn't provide one.

2018-04-07 19:35 UTC, nemo commented
Thanks! Will merge soon!

2018-05-16 11:31 UTC, Kikobeats commented
@nemo merge pls 🙂

2018-10-30 14:19 UTC, yonguelink commented
@nemo Could this be merged?

2018-10-30 14:48 UTC, yonguelink requested changes
I noticed a bug while using the original lib:

The last chunk is just dropped.

I don't know how much sense that makes when you have your transform and (possibly) a flush method, so I wouldn't touch that, but here, when we just relay the batch to the next down the line, I think it makes no sense to drop the batch.

2018-10-30 14:48 UTC, yonguelink commented on through2-batch.js
>                batched = [];
You should probably call `callback(null, batched);` before throwing the batch away.

This way, the last batch is just dropped without notice.

```suggestion
              callback(null, batched);
              batched = [];
```

2018-11-04 17:03 UTC, merged

2018-11-04 17:05 UTC, nemo commented
Merged! Version 1.1.1 has the changes.